name: Publish to PYPI

on:
  push:
    tags:
      - "v-*"

jobs:
  publish:
    name: Build and publish the package to pypi
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install deps
      run: |
        python -m pip install wheel twine build
    
    - name: Build and Publish
      run: python setup.py publish
      env:
        TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
